version: '2'
services:
  docs:
    build:
      context: .
      dockerfile: docs/Dockerfile
    tty: true
    ports:
      - 9999:9999
    volumes:
      - ./docs/www:/var/www
    networks:
      - frontend
  # mysql:
  #   image: mysql:5.7
  #   ports:
  #     - 33060:3306
  #   volumes:
  #     - ./mysql/data:/var/lib/mysql
  #     - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=password
  #   networks:
  #     - frontend

# 将容器置于同一 networks 即可直接通过容器名访问
networks:
  frontend:
    driver: bridge
